### ISSUE TITLE
allow-block-place TNT does not work!

### ISSUE THREAD

**Issue by Leonardo-Fiori** [isokissa3/WorldGuardExtraFlagsPlugin#99] opened 2020-01-17 20:49 UTC
/rg flag test allow-block-place tnt

Hey! Sorry but you can't place that block here.

I wanted to allow the placing of ONLY tnt blocks inside a region, to everyone, also non-members. 

Unfortunately it does not work. I also tried enabling passthrough. The only way to make it work is to use block-place allow, but that allows every block to be placed.

git-Paper-223 (MC: 1.14.4)
WorldGuardExtraFlags version 4.1.2
WorldEdit version 7.0.1;61bc012

**Comment by isokissa3** [comment] 2020-01-17 21:08
This has been long standing bug due to using WG events to rely on which blocks can and can not be placed in order to allow overriding the result.

Dupe of #12

**Closed by isokissa3** 2020-01-17 21:08 UTC
