### ISSUE TITLE
2.14.2

### ISSUE THREAD

**Issue by madtomic** [isokissa3/WorldGuardExtraFlagsPlugin#20] opened 2017-11-07 23:47 UTC
command-on-entry & command-on-exit
console-command-on-entry & console-command-on-exit 

These are still not working.

**Comment by EvilOlaf** [comment] 2017-11-08 08:18
Working nicely for me. Did you make sure that you do not have WorldGuard bypass permission node? Then none of your flags would apply.

**Comment by Pugabyte** [comment] 2017-11-17 20:50
Duplicate of #19

**Comment by madtomic** [comment] 2017-11-24 18:06
worldguard.region.bypass.<world> (gives users with this permission the ability to bypass region protection)

Wouldn't this defeated the purpose to have any kind of protections at all in the first place?

IMO: this change is bad as now I need to give all users the ability to bypass region protections.

**Comment by madtomic** [comment] 2017-11-24 22:04
@EvilOlaf 

I don't have the bypass permission node. Just the normal add greeting and it usually shows up but in new WG. no luck

**Comment by madtomic** [comment] 2017-12-15 00:55
@EvilOlaf What version of WG/WE are you using to get this plugin to work?

**Comment by EvilOlaf** [comment] 2017-12-15 08:19
`WorldGuard 6.1.3-SNAPSHOT;c904242` combined with `WorldGuardExtraFlags version 2.14.3` working decent on `Spigot 1.8.8`

**Comment by isokissa3** [comment] 2018-04-12 19:04
Having permissions to `worldguard.region.bypass.<world>` will prevent the flags from happening, also make sure you have `use-player-move-event` set to true in WorldGuard config

**Closed by isokissa3** 2018-04-12 19:04 UTC
