### ISSUE TITLE
Glide Flag disables on restart

### ISSUE THREAD

**Issue by Sinnethh** [isokissa3/WorldGuardExtraFlagsPlugin#111] opened 2020-04-09 11:27 UTC
I have recently opened my server and have disabled Elytras in certain regions. It all works perfectly fine until the server is restarted or the worldguard config is reloaded. There is no console error messages

**Comment by isokissa3** [comment] 2020-04-09 12:11
Dupe of #105

**Closed by isokissa3** 2020-04-09 12:11 UTC
Labels: duplicate
